# 코딩 테스트 연습 > 탑욕법(Greedy) > 섬 연결하기 

## 문제 설명
n개의 섬 사이에 다리를 건설하는 비용(costs)이 주어질 때, 최소의 비용으로 모든 섬이 서로 통행 가능하도록 만들 때 필요한 최소 비용을 return 하도록 solution을 완성하세요.

다리를 여러 번 건너더라도, 도달할 수만 있으면 통행 가능하다고 봅니다. 예를 들어 A 섬과 B 섬 사이에 다리가 있고, B 섬과 C 섬 사이에 다리가 있으면 A 섬과 C 섬은 서로 통행 가능합니다.

## 제한사항

- 섬의 개수 n은 1 이상 100 이하입니다.
- costs의 길이는 ((n-1) * n) / 2이하입니다.
- 임의의 i에 대해, costs[i][0] 와 costs[i] [1]에는 다리가 연결되는 두 섬의 번호가 들어있고, costs[i] [2]에는 이 두 섬을 연결하는 다리를 건설할 때 드는 비용입니다.
- 같은 연결은 두 번 주어지지 않습니다. 또한 순서가 바뀌더라도 같은 연결로 봅니다. 즉 0과 1 사이를 연결하는 비용이 주어졌을 때, 1과 0의 비용이 주어지지 않습니다.
- 모든 섬 사이의 다리 건설 비용이 주어지지 않습니다. 이 경우, 두 섬 사이의 건설이 불가능한 것으로 봅니다.
- 연결할 수 없는 섬은 주어지지 않습니다.

## 입출력 예

|n|costs|return|
|---|---|---|
|4|[[0,1,1],[0,2,2],[1,2,5],[1,3,1],[2,3,8]]|4|

In [1]:
def solution(n, costs):
    answer = 0
    return answer

In [6]:
n = 4
costs = [[0,1,1],[0,2,2],[1,2,5],[1,3,1],[2,3,8]]
costs

[[0, 1, 1], [0, 2, 2], [1, 2, 5], [1, 3, 1], [2, 3, 8]]

1. 0과 1을 연결하는데 1의 코스트가 든다.
2. 0과 2을 연결하는데 2가 든다.
3. 1과 2를 연결하는데 5가 든다.
4. 1과 3을 연결하는데 1이 든다.
5. 2와 3을 연결하는데 8이 든다.

## 아이디어

1. 결국 가장 낮은 코스트로 섬을 다 연결하는 방법은 모든 섬을 일렬로 연결하는 것이다. 그러면 다리는 n-1개가 된다.
2. 코스트가 가장 낮은 다리부터 연결하는 것이다.
3. 다리를 다 연결하면, 맨 끝의 섬은 1개씩만 남고, 가운데 섬들은 두개가 된다.

In [8]:
import numpy as np

In [10]:
ncosts = np.array(costs)
ncosts

array([[0, 1, 1],
       [0, 2, 2],
       [1, 2, 5],
       [1, 3, 1],
       [2, 3, 8]])

In [13]:
import itertools

In [43]:
cost = []
for i in list(itertools.combinations(costs, n-1)):
    print(i)
    print(np.array(i).sum(axis=0)[2])
    cost.append(np.array(i).sum(axis=0)[2])

([0, 1, 1], [0, 2, 2], [1, 2, 5])
8
([0, 1, 1], [0, 2, 2], [1, 3, 1])
4
([0, 1, 1], [0, 2, 2], [2, 3, 8])
11
([0, 1, 1], [1, 2, 5], [1, 3, 1])
7
([0, 1, 1], [1, 2, 5], [2, 3, 8])
14
([0, 1, 1], [1, 3, 1], [2, 3, 8])
10
([0, 2, 2], [1, 2, 5], [1, 3, 1])
8
([0, 2, 2], [1, 2, 5], [2, 3, 8])
15
([0, 2, 2], [1, 3, 1], [2, 3, 8])
11
([1, 2, 5], [1, 3, 1], [2, 3, 8])
14


In [44]:
min(cost)

4

### 아이디어2

코스트 순으로 정렬을 한 다음, 빠르게 종료한다.

In [49]:
temp = list(itertools.combinations(costs, n-1))
temp

[([0, 1, 1], [0, 2, 2], [1, 2, 5]),
 ([0, 1, 1], [0, 2, 2], [1, 3, 1]),
 ([0, 1, 1], [0, 2, 2], [2, 3, 8]),
 ([0, 1, 1], [1, 2, 5], [1, 3, 1]),
 ([0, 1, 1], [1, 2, 5], [2, 3, 8]),
 ([0, 1, 1], [1, 3, 1], [2, 3, 8]),
 ([0, 2, 2], [1, 2, 5], [1, 3, 1]),
 ([0, 2, 2], [1, 2, 5], [2, 3, 8]),
 ([0, 2, 2], [1, 3, 1], [2, 3, 8]),
 ([1, 2, 5], [1, 3, 1], [2, 3, 8])]

In [60]:
min(np.array(temp).sum(axis=1)[:,2])

4

### 아이디어3

1. itertools는 시간초과로 사용하지 못합니다.
2. set()으로 모든 섬이 들어가 있는지를 확인합니다.

In [82]:
n = 4
ncosts = np.array(costs)
ncosts

array([[0, 1, 1],
       [0, 2, 2],
       [1, 2, 5],
       [1, 3, 1],
       [2, 3, 8]])

In [83]:
np.arange(n)

array([0, 1, 2, 3])

In [84]:
list(itertools.combinations(np.arange(n), n-1))

[(0, 1, 2), (0, 1, 3), (0, 2, 3), (1, 2, 3)]

In [94]:
cost_list = []
for i in list(itertools.combinations(np.arange(n), n-1)):
    if len(set(ncosts[[i],: 2].flatten())) == n: # 만일 섬이 다 들어가 있으면
        cost_list.append(ncosts[[i], 2].sum())

In [95]:
int(min(cost_list))

4

### 뉴 아이디어

itertools를 쓰지 않고 맨 낮은 코스트부터 조합으로 하다가 멈추면 어때?!

In [1]:
n = 4
costs = [[0,1,1],[0,2,2],[1,2,5],[1,3,1],[2,3,8]]
costs

[[0, 1, 1], [0, 2, 2], [1, 2, 5], [1, 3, 1], [2, 3, 8]]

In [2]:
costs.sort(key=lambda x: x[2])

In [3]:
costs

[[0, 1, 1], [1, 3, 1], [0, 2, 2], [1, 2, 5], [2, 3, 8]]

### 혜인이 답안

In [4]:
n = 4
costs = [[0,1,1],[0,2,2],[1,2,5],[1,3,1],[2,3,8]]
costs

[[0, 1, 1], [0, 2, 2], [1, 2, 5], [1, 3, 1], [2, 3, 8]]

In [14]:
answer = []
cost_way = [tuple(x[:2]) for x in costs] #경로 정보 init
print("start cost_way is: ", cost_way)
print("-"*100)

for start_way in cost_way:
    print("start_way is: ", start_way)
    cost_way = [tuple(x[:2]) for x in costs] # cost way를 다시 정의해준다.
    print("new cost_way is: ", cost_way)
    
    way_cost_dict = {tuple(x[:2]):x[2] for x in costs}
    print("way_cost_dict is: ", way_cost_dict)
    
    cost_way.remove(start_way) # 사용한 다리는 지운다.
    connected_group  = list(start_way)
    print("connected_group is: ", connected_group)
    total_cost = way_cost_dict[start_way]
    print("total_cost is: ", total_cost)
    del way_cost_dict[start_way]
    print("deleted way_cost_dict: ", way_cost_dict)

    while len(connected_group) != n: # connected group 이 n의 길이와 다르면
        candidate_ways =[]
        for i in connected_group:
            candidate_ways.extend(list(filter(lambda x: i in x, cost_way)))
            # append는 요소 그대로 하나의 요소로 투입, extend는 요소를 펼쳐서 다수의 요소들로 투입.
            print("candidate_ways is: ", candidate_ways)
            
        min_way = min(candidate_ways, key=lambda x: way_cost_dict[x])
        print("min_way is: ", min_way)
         
        if set(min_way).intersection(set(connected_group)) != set(min_way):            
            connected_group.extend(list(min_way))
            connected_group = list(set(connected_group))
            total_cost+= way_cost_dict[min_way]
            
        del way_cost_dict[min_way]
        
        cost_way.remove(min_way)
        
    answer.append(total_cost)
    
    print("-"*100)
min(answer)

start cost_way is:  [(0, 1), (0, 2), (1, 2), (1, 3), (2, 3)]
----------------------------------------------------------------------------------------------------
start_way is:  (0, 1)
new cost_way is:  [(0, 1), (0, 2), (1, 2), (1, 3), (2, 3)]
way_cost_dict is:  {(0, 1): 1, (0, 2): 2, (1, 2): 5, (1, 3): 1, (2, 3): 8}
connected_group is:  [0, 1]
total_cost is:  1
deleted way_cost_dict:  {(0, 2): 2, (1, 2): 5, (1, 3): 1, (2, 3): 8}
candidate_ways is:  [(0, 2)]
candidate_ways is:  [(0, 2), (1, 2), (1, 3)]
min_way is:  (1, 3)
candidate_ways is:  [(0, 2)]
candidate_ways is:  [(0, 2), (1, 2)]
candidate_ways is:  [(0, 2), (1, 2), (2, 3)]
min_way is:  (0, 2)
----------------------------------------------------------------------------------------------------
start_way is:  (0, 2)
new cost_way is:  [(0, 1), (0, 2), (1, 2), (1, 3), (2, 3)]
way_cost_dict is:  {(0, 1): 1, (0, 2): 2, (1, 2): 5, (1, 3): 1, (2, 3): 8}
connected_group is:  [0, 2]
total_cost is:  2
deleted way_cost_dict:  {(0, 1): 1, (1,

4