# 코딩 테스트 연습 > 풍선 터트리기

## 문제 설명
일렬로 나열된 n개의 풍선이 있습니다. 모든 풍선에는 서로 다른 숫자가 써져 있습니다. 당신은 다음 과정을 반복하면서 풍선들을 단 1개만 남을 때까지 계속 터트리려고 합니다.

1. 임의의 인접한 두 풍선을 고른 뒤, 두 풍선 중 하나를 터트립니다.
2. 터진 풍선으로 인해 풍선들 사이에 빈 공간이 생겼다면, 빈 공간이 없도록 풍선들을 중앙으로 밀착시킵니다.


여기서 조건이 있습니다. 인접한 두 풍선 중에서 번호가 더 작은 풍선을 터트리는 행위는 최대 1번만 할 수 있습니다. 즉, 어떤 시점에서 인접한 두 풍선 중 번호가 더 작은 풍선을 터트렸다면, 그 이후에는 인접한 두 풍선을 고른 뒤 번호가 더 큰 풍선만을 터트릴 수 있습니다.

당신은 어떤 풍선이 최후까지 남을 수 있는지 알아보고 싶습니다. 위에 서술된 조건대로 풍선을 터트리다 보면, 어떤 풍선은 최후까지 남을 수도 있지만, 어떤 풍선은 무슨 수를 쓰더라도 마지막까지 남기는 것이 불가능할 수도 있습니다.

일렬로 나열된 풍선들의 번호가 담긴 배열 a가 주어집니다. 위에 서술된 규칙대로 풍선들을 1개만 남을 때까지 터트렸을 때 최후까지 남기는 것이 가능한 풍선들의 개수를 return 하도록 solution 함수를 완성해주세요.

## 제한 사항
- a의 길이는 1 이상 1,000,000 이하입니다.
    - a[i]는 i+1 번째 풍선에 써진 숫자를 의미합니다.
    - a의 모든 수는 -1,000,000,000 이상 1,000,000,000 이하인 정수입니다.
    - a의 모든 수는 서로 다릅니다.

## 입출력 예
|a	|result|
|---|---|
|[9,-1,-5]	|3|
|[-16,27,65,-2,58,-92,-71,-68,-61,-33]	|6|

## 입출력 예 설명
### 입출력 예 #1

- 첫 번째 풍선(9가 써진 풍선)을 최후까지 남기는 방법은 다음과 같습니다.
    1. [9, -1, -5] 에서 -1, -5가 써진 풍선을 고른 뒤, -1이 써진 풍선(번호가 더 큰 것)을 터트립니다.
    2. [9, -5] 에서 9, -5가 써진 풍선을 고른 뒤, -5가 써진 풍선(번호가 더 작은 것)을 터트립니다.
- 두 번째 풍선(-1이 써진 풍선)을 최후까지 남기는 방법은 다음과 같습니다.
    1. [9, -1, -5] 에서 9, -1이 써진 풍선을 고른 뒤, 9가 써진 풍선(번호가 더 큰 것)을 터트립니다.
    2. [-1, -5] 에서 -1, -5가 써진 풍선을 고른 뒤, -5가 써진 풍선(번호가 더 작은 것)을 터트립니다.
- 세 번째 풍선(-5가 써진 풍선)을 최후까지 남기는 방법은 다음과 같습니다.
    1. [9, -1, -5] 에서 9, -1이 써진 풍선을 고른 뒤, 9가 써진 풍선(번호가 더 큰 것)을 터트립니다.
    2. [-1, -5] 에서 -1, -5가 써진 풍선을 고른 뒤, -1이 써진 풍선(번호가 더 큰 것)을 터트립니다.
- 3개의 풍선이 최후까지 남을 수 있으므로, 3을 return 해야 합니다.

### 입출력 예 #2

- 최후까지 남을 수 있는 풍선은 -16, -92, -71, -68, -61, -33이 써진 풍선으로 모두 6개입니다.

## 아이디어

1. 일단 두 개의 풍선을 고르고, 더 값이 큰 풍선을 터뜨려서 마지막으로 남은 풍선을 리턴하는 모델을 만들어야겠다.

2. 그 다음, 더 작은 값의 풍선을 터뜨릴 수 있는 모델을 끼워 넣어본다.

3. 오히려 해당 숫자가 생존할 수 있는지를 체크한다면?

4. 맨 왼쪽과 맨 오른쪽은 무조건 생존할 수 있다. 왜냐면 찬스 1개를 쓸 수 있으니까. 문제는 가운데인데, 가운데는 양 옆을 모두 이겨야 한다. 찬스를 한 번 밖에 쓰지 못하므로 다른 한 쪽은 무조건 자기보다 숫자가 커야 한다.

5. 가장 작은 수는 무조건 살아남는다.

6. 가장 작은 수보다 바로 위의 큰 수도 무조건 살아남는다.

In [1]:
a = [9, -1, -5]
a_res = 3

b = [-16, 27, 65, -2, 58, -92, -71, -68, -61, -33]
b_res = 6
print(len(b))

10


In [123]:
# 인접한 두 개의 풍선만을 고를 수 있다.
# 무조건 두 개의 풍선 중에 값이 큰 풍선만 터뜨릴 수 있다.
# 단 한 번, 더 작은 값의 풍선을 터뜨릴 수 있다.

In [70]:
import numpy as np

In [71]:
import random as rd

In [446]:
def bomb(list_, start_idx):
    """
    풍선 리스트를 받아서 지정한 인덱스와 그 우측으로 인접한 풍선에 대해 터뜨리고
    다시 풍선 리스트로 넣어주는 함수
    
    인수
    list_ : 풍선 리스트
    start_idx: 풍선 시작점
    """  
    temp = list_[start_idx:start_idx+2]
    if temp[0] > temp[1]:
        temp.pop(0)
    else:
        temp.pop()
    list_[start_idx] = temp[0]
    list_.pop(start_idx+1)

    return list_

In [489]:
b = [-16, 27, 65, -2, 58, -92, -71, -68, -61, -33]
for _ in range(len(b) - 3):
    ranges = rd.randint(0, len(b)-2)
    print("ranges: ", ranges)
    bomb(b, ranges)
    print(b)

ranges:  7
[-16, 27, 65, -2, 58, -92, -71, -68, -33]
ranges:  6
[-16, 27, 65, -2, 58, -92, -71, -33]
ranges:  2
[-16, 27, -2, 58, -92, -71, -33]
ranges:  0
[-16, -2, 58, -92, -71, -33]
ranges:  2
[-16, -2, -92, -71, -33]
ranges:  2
[-16, -2, -92, -33]
ranges:  0
[-16, -92, -33]


In [649]:
b = [-16, 27, 65, -2, 58, -92, -71, -68, -61, -33]

In [536]:
np.where(b)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

In [535]:
np.argmin(b)

5

In [527]:
b[1:-1]

[27, 65, -2, 58, -92, -71, -68, -61]

In [2]:
survivor = 2
input_ = b
enu_input = input_[1:-1]
for i, j in enumerate(enu_input):

    print("when i == {}, j is: ".format(i), j)
    print("left pool is : ", input_[0:i+1])
    print("left min number is: ", min(input_[0:i+1]))
    print("right pool is : ", input_[i+2:])
    print("right min number is: ", min(input_[i+2:]))

    left = min(input_[0:i+1])
    right = min(input_[i+2:])

    if left > j or right > j:
        print("left < j: ", left > j)
        print("rigth < j: ", right > j)
        print(j, " is alive.")
        survivor += 1
            
survivor

when i == 0, j is:  27
left pool is :  [-16]
left min number is:  -16
right pool is :  [65, -2, 58, -92, -71, -68, -61, -33]
right min number is:  -92
when i == 1, j is:  65
left pool is :  [-16, 27]
left min number is:  -16
right pool is :  [-2, 58, -92, -71, -68, -61, -33]
right min number is:  -92
when i == 2, j is:  -2
left pool is :  [-16, 27, 65]
left min number is:  -16
right pool is :  [58, -92, -71, -68, -61, -33]
right min number is:  -92
when i == 3, j is:  58
left pool is :  [-16, 27, 65, -2]
left min number is:  -16
right pool is :  [-92, -71, -68, -61, -33]
right min number is:  -92
when i == 4, j is:  -92
left pool is :  [-16, 27, 65, -2, 58]
left min number is:  -16
right pool is :  [-71, -68, -61, -33]
right min number is:  -71
left < j:  True
rigth < j:  True
-92  is alive.
when i == 5, j is:  -71
left pool is :  [-16, 27, 65, -2, 58, -92]
left min number is:  -92
right pool is :  [-68, -61, -33]
right min number is:  -68
left < j:  False
rigth < j:  True
-71  is aliv

6

In [3]:
survivor

6

추가 아이디어.

1. 가장 작은 친구를 구한다.
2. 가장 작은 친구를 기점으로 좌우 끝 친구들보다 큰 애들만 산다.
3. 맨 끝 둘은 무조건 산다.

In [6]:
import numpy as np

In [7]:
b = [-16, 27, 65, -2, 58, -92, -71, -68, -61, -33]

In [8]:
np.where(b)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

In [10]:
min_idx = np.argmin(b)
min_idx

5

In [11]:
lefts = b[:min_idx]
print(lefts)
rights = b[min_idx+1:]
print(rights)

[-16, 27, 65, -2, 58]
[-71, -68, -61, -33]


In [12]:
b[0], b[len(b)-1]

(-16, -33)

In [13]:
print(np.where(np.array(lefts) > b[0], 0, 1))
print(np.where(np.array(lefts) > b[0], 0, 1).sum())

[1 0 0 0 0]
1


In [14]:
print(np.where(np.array(rights) > b[len(b)-1], 0, 1))
print(np.where(np.array(rights) > b[len(b)-1], 0, 1).sum())

[1 1 1 1]
4


In [15]:
i = b

In [16]:
min_idx = np.argmin(i)

lefts = np.array(i[:min_idx])
rights = np.array(i[min_idx+1:])
survivor = (1
            + np.where(lefts > i[0], 0, 1).sum()
            + np.where(rights > i[len(i)-1], 0, 1).sum()
           )

survivor

6

추가 아이디어.

두번째 아이디어에서 확 땡겨버리는 것은?

In [42]:
import numpy as np
mini = []
mini.append(b[np.argmin(b)])
left = b[:np.argmin(b)]
print(left)
right = b[np.argmin(b)+1:]
print(right)

[-16, 27, 65, -2, 58]
[-71, -68, -61, -33]


In [43]:
left_left = left[:np.argmin(left)]
print(left_left)
right_right = right[np.argmin(right)+1:]
print(right_right)

[]
[-68, -61, -33]


In [44]:
mini.append(left_left)
mini.append(right_right)
mini

[-92, [], [-68, -61, -33]]

In [55]:
survivor = 2
input_ = b
enu_input = input_[1:-1]
for i, j in enumerate(enu_input):

    print("when i == {}, j is: ".format(i), j)
    print("left pool is : ", input_[0:i+1])
    print("left min number is: ", min(input_[0:i+1]))
    print("right pool is : ", input_[i+2:])
    print("right min number is: ", min(input_[i+2:]))

    left = min(input_[0:i+1])
    right = min(input_[i+2:])

    if left < j and right < j:
        print("left < j: ", left > j)
        print("rigth < j: ", right > j)
        print(j, " is alive.")
    else:
        survivor += 1
            
survivor

when i == 0, j is:  27
left pool is :  [-16]
left min number is:  -16
right pool is :  [65, -2, 58, -92, -71, -68, -61, -33]
right min number is:  -92
left < j:  False
rigth < j:  False
27  is alive.
when i == 1, j is:  65
left pool is :  [-16, 27]
left min number is:  -16
right pool is :  [-2, 58, -92, -71, -68, -61, -33]
right min number is:  -92
left < j:  False
rigth < j:  False
65  is alive.
when i == 2, j is:  -2
left pool is :  [-16, 27, 65]
left min number is:  -16
right pool is :  [58, -92, -71, -68, -61, -33]
right min number is:  -92
left < j:  False
rigth < j:  False
-2  is alive.
when i == 3, j is:  58
left pool is :  [-16, 27, 65, -2]
left min number is:  -16
right pool is :  [-92, -71, -68, -61, -33]
right min number is:  -92
left < j:  False
rigth < j:  False
58  is alive.
when i == 4, j is:  -92
left pool is :  [-16, 27, 65, -2, 58]
left min number is:  -16
right pool is :  [-71, -68, -61, -33]
right min number is:  -71
when i == 5, j is:  -71
left pool is :  [-16, 27,

6