# 코딩테스트 연습 > 그리디 > 체육복

본 문제의 저작권은 주식회사 프로그래머스에 있습니다. 문제를 풀고 싶으시다면 해당 회사의 웹사이트로 가시면 됩니다.

## 문제 설명
점심시간에 도둑이 들어, 일부 학생이 체육복을 도난당했습니다. 다행히 여벌 체육복이 있는 학생이 이들에게 체육복을 빌려주려 합니다. 학생들의 번호는 체격 순으로 매겨져 있어, 바로 앞번호의 학생이나 바로 뒷번호의 학생에게만 체육복을 빌려줄 수 있습니다. 예를 들어, 4번 학생은 3번 학생이나 5번 학생에게만 체육복을 빌려줄 수 있습니다. 체육복이 없으면 수업을 들을 수 없기 때문에 체육복을 적절히 빌려 최대한 많은 학생이 체육수업을 들어야 합니다.

전체 학생의 수 n, 체육복을 도난당한 학생들의 번호가 담긴 배열 lost, 여벌의 체육복을 가져온 학생들의 번호가 담긴 배열 reserve가 매개변수로 주어질 때, 체육수업을 들을 수 있는 학생의 최댓값을 return 하도록 solution 함수를 작성해주세요.

### 제한사항
1. 전체 학생의 수는 2명 이상 30명 이하입니다.
2. 체육복을 도난당한 학생의 수는 1명 이상 n명 이하이고 중복되는 번호는 없습니다.
3. 여벌의 체육복을 가져온 학생의 수는 1명 이상 n명 이하이고 중복되는 번호는 없습니다.
4. 여벌 체육복이 있는 학생만 다른 학생에게 체육복을 빌려줄 수 있습니다.
5. 여벌 체육복을 가져온 학생이 체육복을 도난당했을 수 있습니다. 이때 이 학생은 체육복을 하나만 도난당했다고 가정하며, 6. 남은 체육복이 하나이기에 다른 학생에게는 체육복을 빌려줄 수 없습니다.

In [1]:
def solution(n, lost, reserve):
    import numpy as np
    
    tw = np.int16(np.ones(n))
    lost = np.array(np.int16(lost)) - 1
    res = np.array(np.int16(reserve)) - 1
    
    tw[lost] -= 1
    tw[res] += 1
    
    for i in range(len(tw)):
        try:
            if tw[i] - tw[i + 1] == 2:
                tw[i + 1] += 1
                tw[i] -= 1
            elif tw[i] - tw[i + 1] == -2:
                tw[i] += 1
                tw[i + 1] -= 1

        except:
            pass
    
    return np.sum(np.where(tw >=1., 1., 0))

In [6]:
n = 5
lost = [2, 4]
reserve = [1, 3, 5]

In [56]:
n = 5
lost = [1, 3, 5]
reserve = [2, 4]

In [57]:
tw = np.int16(np.ones(n))
lost = np.array(np.int16(lost)) - 1
res = np.array(np.int16(reserve)) - 1

tw[lost] -= 1
tw[res] += 1

for i in lost:

    if i == 0:
        if tw[i + 1] == 2:
            tw[[i, i+1]] = 1
    elif i == len(tw)-1:
        if tw[i - 1] == 2:
            tw[[i-1, i]] = 1
    else:
        if tw[i] - tw[i + 1] == 2:
            tw[[i-1, i]] += 1
        elif tw[i] - tw[i + 1] == -2:
            tw[i, i + 1] += 1
np.sum(np.where(tw >=1., 1., 0))

4.0

In [49]:
tw = np.int16(np.ones(n))
lost = np.array(np.int16(lost)) - 1
res = np.array(np.int16(reserve)) - 1

tw[lost] -= 1
tw[res] += 1

In [52]:
len(tw)

5

In [50]:
tw

array([0, 2, 0, 2, 0], dtype=int16)

In [51]:
lost

array([0, 2, 4], dtype=int16)

In [39]:
tw[-1]

1

In [33]:
lost

array([0], dtype=int16)

In [32]:
tw

array([1, 1, 1, 1, 1], dtype=int16)

In [19]:
tw = np.int16(np.ones(n))
lost = np.array(np.int16(lost)) - 1
res = np.array(np.int16(reserve)) - 1

In [20]:
tw

array([1, 1, 1, 1], dtype=int16)

In [21]:
lost

array([0, 2], dtype=int16)

In [22]:
res

array([1], dtype=int16)

In [24]:
tw[lost] = tw[lost] - 1

In [25]:
tw

array([0, 1, 0, 1], dtype=int16)

In [27]:
tw[res] = tw[res] + 1

In [28]:
tw

array([0, 2, 0, 1], dtype=int16)

In [29]:
lost

array([0, 2], dtype=int16)

In [ ]:
def solution(n, lost, reserve):

    answer = np.ones(n)
    lost_idx = np.array(lost)
    res_idx = np.array(reserve)

    answer[lost_idx-1] -= 1
    answer[res_idx-1] += 1

    for i in range(len(answer)):
        try:
            if answer[i] - answer[i + 1] == 2:
                answer[i + 1] += 1
                answer[i] -= 1
            elif answer[i] - answer[i + 1] == -2:
                answer[i] += 1
                answer[i + 1] -= 1

        except:
            pass

    answer = np.where(answer >= 2, 1, answer)

    return int(np.sum(answer))